//GET
export const NEWS_GET_REQUEST = "NEWS_GET_REQUEST"
export const NEWS_GET_SUCCESS = "NEWS_GET_SUCCESS"
export const NEWS_GET_FAIL = "NEWS_GET_FAIL"

//POST
export const NEWS_POST_REQUEST = "NEWS_POST_REQUEST "
export const NEWS_POST_SUCCESS = "NEWS_POST_SUCCESS"
export const NEWS_POST_FAIL = "NEWS_POST_FAIL"

//DELETE
export const NEWS_DELETE_REQUEST = "NEWS_DELETE_REQUEST "
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS"
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL"

//VIEW
export const NEWS_VIEW_REQUEST = "NEWS_VIEW_REQUEST "
export const NEWS_VIEW_SUCCESS = "NEWS_VIEW_SUCCESS"
export const NEWS_VIEW_FAIL = "NEWS_VIEW_FAIL"

//Update

export const NEWS_UPDATE_REQUEST = "NEWS_UPDATE_REQUEST "
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS"
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL"

//empty
export const NEWS_EMPTY_ID = "NEWS_EMPTY_ID "


//Login_Admin
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"

export const ADMIN_POST_REQUEST = "ADMIN_POST_REQUEST"
export const ADMIN_POST_SUCCESS = "ADMIN_POST_SUCCESS"
export const ADMIN_POST_FAIL = "ADMIN_POST_FAIL"



//Logout-Admin
export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

//Sign Up User
export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL"

//dublicate
export const DUPLICATE_DATA = 'DUPLICATE_DATA';



